version: '3'

services:
  client:
    image: "${CLIENT_DOCKER_IMAGE}"
    container_name: client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - app

  app:
    image: "${SERVER_DOCKER_IMAGE}"
    container_name: app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_TOKENS=${GITHUB_TOKENS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - ai-server

  ai-server:
    image: "${AI_SERVER_IMAGE}"
    container_name: ai-server
    ports:
      - "${AI_SERVER_PORT}:${AI_SERVER_PORT}"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/

volumes:
  db_data: