spring:
  profiles:
    active:
      - prod

client:
  url: https://osore.kr
  github:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
    tokens: ${GITHUB_TOKENS}
  google:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

