spring:
  profiles:
    active: local

client:
  url: http://localhost:3000
  github:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
    tokens: ${GITHUB_TOKENS}
  google:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

